### ISSUE TITLE
Inclusion/exclusion of countries with new epidemics

### ISSUE THREAD

**Issue by salervm1** [calthaus/ncov-cfr#5]
With many new local outbreaks (and more to come), how are you going to proceed with updating the analysis? Specifically, are countries going to be included/excluded from the analysis in order to retain the ability to catch the whole spectrum of disease, or will all data be included? I presume that expanding epidemics in countries with poor surveillance could result in data that is biased towards severe cases, as in the case of Hubei province.

Bonus question: is there a book on epidemiology you would recommend for someone with a math/comp sci background?

**Comment by calthaus** [comment]
You're exactly right. Including the cases in Iran or Italy, for example, would introduce an undesired bias in our analysis. We will probably stop updating the real-time estimation or limit the analysis to countries where we hope to have (almost) complete surveillance.

There are a number of books that could be of interest for you:
- Diekmann et al. Mathematical Tools for Understanding Infectious Disease Dynamics.
- Keeling & Rohani. Modeling Infectious Diseases in Humans and Animals.
- Vynnycky & White. An Introduction to Infectious Disease Modelling.

**Comment by salervm1** [comment]
Thanks for your reply and recommendations!

**Comment by umran** [comment]
Would the Diamond Princess be a good sample to estimate CFR from? I ask because probably all cases were detected by testing the whole population onboard. If the population onboard is not too biased and people were infected randomly, perhaps it could tell us a thing or two about the clinical spectrum of COVID-19 we might expect to see in a larger population?
